# gitlab ci service
# https://cern.service-now.com/service-portal/article.do?n=KB0003690
# https://gitlab.cern.ch/help/ci/yaml/README.md

# use the default image for build (currently slc7)
# image: slc6

build:
  stage: test

  tags:
  # Make your job be executed in a shared runner that has CVMFS mounted
  - cvmfs

  # prepare environment
  before_script:
    - yum -q -y install libX11 libX11-devel motif motif-devel mesa-libGL-devel mesa-libEGL-devel
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_100 x86_64-centos7-gcc9-opt
    #- source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_96b x86_64-centos7-gcc62-opt
    #- export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.5.2/Linux-x86_64/bin:${PATH}
    - cat /etc/redhat-release
    - g++ --version
    - cmake --version
    - root-config --version
    - root-config --features

  # build and test DMG4
  script:
    - ./runconfigure_lcg
    - make
    - make install

    - cd examples/example1
    - ./runconfigure
    - make
    - ./mkgeant4
    - cd ../..
    
  # test DMG4 cross section stability
    - cd examples/testCS
    - ./runconfigure
    
    - sed -r 's#DM_TYPE_NAME#DarkPhotons#g' mkgeant4.cc.template > mkgeant4.cc
    - make
    - mv mkgeant4.cc mkgeant4DP
    - ./mkgeant4 > testDP.log

    - sed -r 's#DM_TYPE_NAME#DarkScalars#g' mkgeant4.cc.template > mkgeant4.cc
    - make
    - mv mkgeant4.cc mkgeant4SC
    - ./mkgeant4 > testSC.log
    
    - sed -r 's#DM_TYPE_NAME#DarkPseudoScalars#g' mkgeant4.cc.template > mkgeant4.cc
    - make
    - mv mkgeant4.cc mkgeant4PS
    - ./mkgeant4 > testPS.log
    
    - sed -r 's#DM_TYPE_NAME#DarkAxials#g' mkgeant4.cc.template > mkgeant4.cc
    - make
    - mv mkgeant4.cc mkgeant4AX
    - ./mkgeant4 > testAX.log

check-tabs:
  stage: test
  
  script:
    - cd src
    - echo "List of files with TAB char:"
    - echo '! grep -r -nP "\t" *' | bash
    - echo "List of files with CR char:"
    - grep -r -lP "\r" * || true
    - cd -
    - cd include
    - echo "List of files with TAB char:"
    - echo '! grep -r -nP "\t" *' | bash
    - echo "List of files with CR char:"
    - grep -r -lP "\r" * || true
    - cd -

test-simu:
  stage: deploy
  trigger: P348/na64-simulation
