# gitlab ci service
# https://cern.service-now.com/service-portal/article.do?n=KB0003690
# https://gitlab.cern.ch/help/ci/yaml/README.md

# use the default image for build (currently slc7)
# image: slc6

build:
  stage: build

  tags:
  # Make your job be executed in a shared runner that has CVMFS mounted
  - cvmfs

  # install the necessary build tools
  before_script:
    - yum -q -y remove mesa-libEGL
    - yum -q -y remove mesa-libGL
    - yum -q -y install libX11 libX11-devel mesa-libEGL mesa-libGL

  # build and test DMG4 and na64-tools/geant4/simulation
  script:
    - cat /etc/redhat-release
    - ls -l /lib64/libEGL*
    - ls -l /lib64/libGL*
    #- cd /lib64
    #- ln -fs libEGL.so.1.1.0 libEGL.so
    #- cd -

    - cd src
    - echo "List of files with TAB char:"
    - echo '! grep -r -nP "\t" *' | bash
    - echo "List of files with CR char:"
    - grep -r -lP "\r" * || true
    - cd -
    - cd include
    - echo "List of files with TAB char:"
    - echo '! grep -r -nP "\t" *' | bash
    - echo "List of files with CR char:"
    - grep -r -lP "\r" * || true
    - cd -

    #- source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_96b x86_64-centos7-gcc62-opt
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_100 x86_64-centos7-gcc9-opt
    #- export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.5.2/Linux-x86_64/bin:${PATH}
    - cmake --version
    - ./runconfigure_lcg
    - make
    - make install
