# gitlab ci service
# https://cern.service-now.com/service-portal/article.do?n=KB0003690
# https://gitlab.cern.ch/help/ci/yaml/README.md

# use the default image for build (currently slc7)
# image: slc6

build:
  stage: test

  tags:
  # Make your job be executed in a shared runner that has CVMFS mounted
  - cvmfs

  # install the necessary build tools
  before_script:
    - yum -q -y install libX11 libX11-devel ghc-OpenGL ghc-OpenGL-devel motif motif-devel

  # build and test DMG4
  script:
    # reparing EGL and GL links
    - cat /etc/redhat-release
    - ls -l /lib64/libEGL*
    - ls -l /lib64/libGL*
    - cd /lib64
    - ln -fs libEGL.so.1.1.0 libEGL.so
    - ln -fs libGL.so.1.7.0 libGL.so
    - cd -

    #- source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_96b x86_64-centos7-gcc62-opt
    - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_100 x86_64-centos7-gcc9-opt
    #- export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.5.2/Linux-x86_64/bin:${PATH}
    - cmake --version
    - ./runconfigure_lcg
    - make
    - make install

    - cd examples/example1
    - ./runconfigure
    - make
    - ./mkgeant4

check-tabs:
  stage: test
  
  script:
    - cd src
    - echo "List of files with TAB char:"
    - echo '! grep -r -nP "\t" *' | bash
    - echo "List of files with CR char:"
    - grep -r -lP "\r" * || true
    - cd -
    - cd include
    - echo "List of files with TAB char:"
    - echo '! grep -r -nP "\t" *' | bash
    - echo "List of files with CR char:"
    - grep -r -lP "\r" * || true
    - cd -

test-simu:
  stage: deploy
  trigger: P348/na64-simulation
