#!/bin/bash
#This is for tests, not for users. Don't change!

GEANT4LOCATION=`geant4-config --prefix`
GSLLOCATION=`gsl-config --prefix`
echo "GEANT4LOCATION=${GEANT4LOCATION}"
echo "GSLLOCATION=${GSLLOCATION}"
#
echo "GEANT4LOCATION=${GEANT4LOCATION}" > config.txt
echo "GSLLOCATION=${GSLLOCATION}" >> config.txt
#
# Enable debug mode during gitlab CI for coverage
./configure --with-geant4=${GEANT4LOCATION} --with-gsl=${GSLLOCATION} --enable-debug
